name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  publish-docker:
    name: "Publish Docker image to DockerHub"
    if: "github.event_name == 'push'"
    concurrency: docker_publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: veridise/picus:git-latest , veridise/picus:git-${{ github.sha }}

  test:

    runs-on: ubuntu-latest
    container: docker/picus:git-latest

    steps:
      - uses: actions/checkout@v1
      - name: compile circomlib
        run: bash ./scripts/prepare-circomlib.sh